"""Generate Markdown reports from forensic sessions or payloads."""

from __future__ import annotations

import logging
from datetime import UTC, datetime
from pathlib import Path
from typing import TYPE_CHECKING

from dfireballz.models.base import ForensicSession
from dfireballz.reporting.html_generator import SEVERITY_ORDER
from dfireballz.reporting.paths import get_report_path

if TYPE_CHECKING:
    from dfireballz.models.forensic_payload import ForensicPayload

logger = logging.getLogger("dfireballz.reporting.md_generator")


def _severity_icon(sev: str) -> str:
    return {
        "critical": "[CRITICAL]",
        "high": "[HIGH]",
        "medium": "[MEDIUM]",
        "low": "[LOW]",
        "info": "[INFO]",
    }.get(sev.lower(), "[?]")


def generate_md_report(
    session: ForensicSession,
    output_path: str | None = None,
) -> Path:
    """Generate a Markdown report from a forensic session.

    Args:
        session: Completed forensic session with findings.
        output_path: Override output file path.

    Returns:
        Path to the generated Markdown file.
    """
    generated_at = datetime.now(UTC).strftime("%Y-%m-%d %H:%M UTC")

    findings_sorted = sorted(
        session.findings,
        key=lambda f: SEVERITY_ORDER.get(
            f.severity if isinstance(f.severity, str) else f.severity.value, 99
        ),
    )

    severity_counts = session.severity_counts
    total_findings = len(session.findings)

    lines: list[str] = []
    lines.append("# DFIReballz Forensic Investigation Report")
    lines.append("")
    lines.append(f"**Target:** {session.target.value}  ")
    lines.append(f"**Session:** {session.id}  ")
    if session.case_id:
        lines.append(f"**Case:** {session.case_id}  ")
    lines.append(f"**Date:** {generated_at}  ")
    if session.duration_seconds is not None:
        lines.append(f"**Duration:** {session.duration_seconds:.1f}s  ")
    lines.append("")

    # Executive Summary
    lines.append("## Executive Summary")
    lines.append("")
    lines.append("| Severity | Count |")
    lines.append("|----------|-------|")
    for sev in ["critical", "high", "medium", "low", "info"]:
        count = severity_counts.get(sev, 0)
        lines.append(f"| {_severity_icon(sev)} {sev.upper()} | {count} |")
    lines.append("")

    # Tools Executed
    lines.append("## Tools Executed")
    lines.append("")
    if session.tools_executed:
        for tool in session.tools_executed:
            lines.append(f"- `{tool}`")
    else:
        lines.append("_No tools recorded._")
    lines.append("")

    # Findings
    lines.append(f"## Findings ({total_findings})")
    lines.append("")

    for finding in findings_sorted:
        sev = finding.severity if isinstance(finding.severity, str) else finding.severity.value
        lines.append(f"### {_severity_icon(sev)} {finding.title}")
        lines.append("")
        lines.append(f"**Severity:** {sev.upper()}  ")
        lines.append(f"**Tool:** {finding.tool}  ")
        lines.append("")

        if finding.description:
            desc = finding.description[:3000]
            lines.append("**Description:**")
            lines.append("```")
            lines.append(desc)
            lines.append("```")
            lines.append("")

        if finding.evidence:
            evidence = finding.evidence[:2000]
            lines.append("**Evidence:**")
            lines.append("```")
            lines.append(evidence)
            lines.append("```")
            lines.append("")

        if finding.recommendation:
            lines.append(f"> **Recommendation:** {finding.recommendation}")
            lines.append("")

        lines.append("---")
        lines.append("")

    # Footer
    lines.append("*Generated by DFIReballz v2.0.0 — AI-Native Digital Forensics Platform*  ")
    lines.append("*This report is confidential. Chain of custody must be maintained.*")
    lines.append("")

    md_content = "\n".join(lines)

    if output_path:
        out = Path(output_path)
    else:
        out = get_report_path(session.target.value, "md")

    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(md_content, encoding="utf-8")
    logger.info("Markdown report generated: %s", out)
    return out


def generate_md_report_from_payload(
    payload: ForensicPayload,
    output_path: str | None = None,
) -> Path:
    """Generate a Markdown report from a ForensicPayload.

    Args:
        payload: Aggregated forensic data from the MCP host.
        output_path: Override output file path.

    Returns:
        Path to the generated Markdown file.
    """
    generated_at = datetime.now(UTC).strftime("%Y-%m-%d %H:%M UTC")

    lines: list[str] = []
    lines.append("# DFIReballz Forensic Investigation Report")
    lines.append("")
    lines.append(f"**Target:** {payload.target}  ")
    lines.append(f"**Session:** {payload.session_id}  ")
    if payload.case_id:
        lines.append(f"**Case:** {payload.case_id}  ")
    lines.append(f"**Date:** {generated_at}  ")
    lines.append("")

    if payload.metadata.warning:
        lines.append(f"> **Warning:** {payload.metadata.warning}")
        lines.append("")

    # Executive Summary
    if payload.executive_summary.headline:
        lines.append("## Executive Summary")
        lines.append("")
        lines.append(f"**Risk Level:** {payload.executive_summary.risk_level.upper()}  ")
        lines.append(f"**{payload.executive_summary.headline}**")
        lines.append("")
        if payload.executive_summary.summary:
            lines.append(payload.executive_summary.summary)
            lines.append("")

    # Tools
    lines.append("## Tools Used")
    lines.append("")
    for tool in payload.metadata.tools_run:
        lines.append(f"- `{tool}`")
    lines.append("")

    # IoCs
    if payload.findings.iocs:
        lines.append(f"## Indicators of Compromise ({len(payload.findings.iocs)})")
        lines.append("")
        lines.append("| Type | Value | Confidence | Context |")
        lines.append("|------|-------|------------|---------|")
        for ioc in payload.findings.iocs:
            lines.append(f"| {ioc.ioc_type} | `{ioc.value}` | {ioc.confidence} | {ioc.context} |")
        lines.append("")

    # Malware Samples
    if payload.findings.malware_samples:
        lines.append(f"## Malware Samples ({len(payload.findings.malware_samples)})")
        lines.append("")
        for sample in payload.findings.malware_samples:
            lines.append(f"### {sample.filename or sample.sha256[:16]}")
            lines.append("")
            if sample.sha256:
                lines.append(f"**SHA256:** `{sample.sha256}`  ")
            if sample.malware_family:
                lines.append(f"**Family:** {sample.malware_family}  ")
            if sample.yara_matches:
                lines.append(f"**YARA:** {', '.join(sample.yara_matches)}  ")
            if sample.mitre_techniques:
                lines.append(f"**MITRE:** {', '.join(sample.mitre_techniques)}  ")
            lines.append("")

    # Timeline
    if payload.findings.timeline_events:
        lines.append(f"## Timeline ({len(payload.findings.timeline_events)} events)")
        lines.append("")
        lines.append("| Timestamp | Type | Source | Description |")
        lines.append("|-----------|------|--------|-------------|")
        for evt in payload.findings.timeline_events[:50]:
            ts = evt.timestamp
            lines.append(
                f"| {ts} | {evt.event_type} | {evt.source} "
                f"| {evt.description} |"
            )
        if len(payload.findings.timeline_events) > 50:
            remaining = len(payload.findings.timeline_events) - 50
            lines.append(
                f"| ... | ... | ... | *{remaining} more events* |"
            )
        lines.append("")

    # Chain of Custody
    if payload.chain_of_custody:
        lines.append(f"## Chain of Custody ({len(payload.chain_of_custody)} entries)")
        lines.append("")
        lines.append("| Timestamp | Action | Evidence | Description |")
        lines.append("|-----------|--------|----------|-------------|")
        for coc in payload.chain_of_custody:
            lines.append(
                f"| {coc.timestamp} | {coc.action} "
                f"| {coc.evidence_id} | {coc.description} |"
            )
        lines.append("")

    # Recommendations
    if payload.recommendations:
        lines.append("## Recommendations")
        lines.append("")
        for rec in sorted(payload.recommendations, key=lambda r: r.priority):
            lines.append(f"### P{rec.priority}: {rec.title}")
            lines.append(f"**Category:** {rec.category} | **Effort:** {rec.effort}")
            lines.append("")
            lines.append(rec.description)
            lines.append("")

    # Metadata
    lines.append("## Investigation Metadata")
    lines.append("")
    lines.append("| Metric | Value |")
    lines.append("|--------|-------|")
    lines.append(f"| Total Artifacts | {payload.metadata.total_artifacts} |")
    lines.append(f"| Total IoCs | {payload.metadata.total_iocs} |")
    lines.append(f"| AI Model | {payload.metadata.model} |")
    lines.append(f"| Duration | {payload.metadata.duration_seconds:.1f}s |")
    lines.append("")

    # Footer
    lines.append("*Generated by DFIReballz v2.0.0 — AI-Native Digital Forensics Platform*  ")
    lines.append("*This report is confidential. Chain of custody must be maintained.*")
    lines.append("")

    md_content = "\n".join(lines)

    if output_path:
        out = Path(output_path)
    else:
        out = get_report_path(payload.target, "md")

    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(md_content, encoding="utf-8")
    logger.info("Markdown report (payload) generated: %s", out)
    return out
