import { useState } from 'react';
import {
  FileText,
  Download,
  Copy,
  CheckCircle,
  Loader2,
  FileDown,
  Eye,
} from 'lucide-react';
import {
  type Case,
  type Finding,
  type IoC,
  type TimelineEvent,
  formatDate,
  cn,
} from '../lib/utils';

interface ReportExportProps {
  caseData: Case;
  findings: Finding[];
  iocs: IoC[];
  timeline: TimelineEvent[];
}

export default function ReportExport({ caseData, findings, iocs, timeline }: ReportExportProps) {
  const [exporting, setExporting] = useState<string | null>(null);
  const [copied, setCopied] = useState(false);
  const [previewMode, setPreviewMode] = useState(true);

  const generateMarkdown = (): string => {
    const lines: string[] = [];

    lines.push(`# Digital Forensics Investigation Report`);
    lines.push('');
    lines.push(`**Case Number:** ${caseData.case_number}`);
    lines.push(`**Title:** ${caseData.title}`);
    lines.push(`**Classification:** ${caseData.classification}`);
    lines.push(`**Severity:** ${caseData.severity.toUpperCase()}`);
    lines.push(`**Status:** ${caseData.status.replace('_', ' ')}`);
    lines.push(`**Investigator:** ${caseData.investigator}`);
    lines.push(`**Created:** ${formatDate(caseData.created_at)}`);
    lines.push(`**Last Updated:** ${formatDate(caseData.updated_at)}`);
    lines.push('');

    lines.push('## Executive Summary');
    lines.push('');
    lines.push(caseData.description);
    lines.push('');

    lines.push(`## Key Metrics`);
    lines.push('');
    lines.push(`| Metric | Count |`);
    lines.push(`|--------|-------|`);
    lines.push(`| IOCs Identified | ${iocs.length} |`);
    lines.push(`| Findings | ${findings.length} |`);
    lines.push(`| Timeline Events | ${timeline.length} |`);
    lines.push('');

    if (findings.length > 0) {
      lines.push('## Findings');
      lines.push('');
      findings.forEach((f, i) => {
        lines.push(`### ${i + 1}. ${f.title}`);
        lines.push('');
        lines.push(`**Severity:** ${f.severity.toUpperCase()} | **Category:** ${f.category}`);
        lines.push('');
        lines.push(f.description);
        lines.push('');
      });
    }

    if (iocs.length > 0) {
      lines.push('## Indicators of Compromise');
      lines.push('');
      lines.push('| Type | Value | Severity | Source |');
      lines.push('|------|-------|----------|--------|');
      iocs.forEach((ioc) => {
        const val = ioc.value.length > 50 ? ioc.value.substring(0, 50) + '...' : ioc.value;
        lines.push(`| ${ioc.type} | \`${val}\` | ${ioc.severity} | ${ioc.source} |`);
      });
      lines.push('');
    }

    if (timeline.length > 0) {
      lines.push('## Timeline');
      lines.push('');
      timeline.forEach((e) => {
        lines.push(`- **${formatDate(e.timestamp)}** [${e.source}] ${e.description}`);
      });
      lines.push('');
    }

    lines.push('## Recommendations');
    lines.push('');
    lines.push('1. Implement additional monitoring for identified IOCs');
    lines.push('2. Review and remediate affected systems');
    lines.push('3. Update detection rules based on findings');
    lines.push('4. Conduct follow-up review in 30 days');
    lines.push('');
    lines.push('---');
    lines.push(`*Report generated by DFIReballz on ${formatDate(new Date())}*`);

    return lines.join('\n');
  };

  const markdown = generateMarkdown();

  const handleCopy = () => {
    navigator.clipboard.writeText(markdown);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleExportMarkdown = () => {
    setExporting('md');
    const blob = new Blob([markdown], { type: 'text/markdown' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${caseData.case_number}-report.md`;
    a.click();
    URL.revokeObjectURL(url);
    setTimeout(() => setExporting(null), 1000);
  };

  const handleExportPDF = () => {
    setExporting('pdf');
    // In production, this would call a server-side PDF generation endpoint
    // For now, we use the browser's print functionality
    const printWindow = window.open('', '_blank');
    if (printWindow) {
      printWindow.document.write(`
        <html>
          <head>
            <title>${caseData.case_number} - Report</title>
            <style>
              body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif; max-width: 800px; margin: 40px auto; color: #1a1a1a; line-height: 1.6; }
              h1 { border-bottom: 2px solid #1F6FEB; padding-bottom: 8px; }
              h2 { color: #1F6FEB; margin-top: 24px; }
              h3 { color: #333; }
              table { border-collapse: collapse; width: 100%; margin: 12px 0; }
              th, td { border: 1px solid #ddd; padding: 8px; text-align: left; font-size: 13px; }
              th { background-color: #f5f5f5; }
              code { background: #f0f0f0; padding: 2px 6px; border-radius: 3px; font-size: 12px; }
              pre { background: #f5f5f5; padding: 12px; border-radius: 4px; overflow-x: auto; }
              strong { color: #333; }
            </style>
          </head>
          <body>${markdownToHtml(markdown)}</body>
        </html>
      `);
      printWindow.document.close();
      printWindow.print();
    }
    setTimeout(() => setExporting(null), 1000);
  };

  return (
    <div className="space-y-4">
      {/* Toolbar */}
      <div className="flex items-center justify-between flex-wrap gap-3">
        <div className="flex items-center gap-2">
          <button
            onClick={() => setPreviewMode(true)}
            className={cn(
              'px-3 py-1.5 rounded-md text-xs font-medium transition-colors flex items-center gap-1.5',
              previewMode
                ? 'bg-accent text-white'
                : 'bg-surface border border-surface-border text-text-secondary hover:border-accent/30'
            )}
          >
            <Eye className="w-3 h-3" />
            Preview
          </button>
          <button
            onClick={() => setPreviewMode(false)}
            className={cn(
              'px-3 py-1.5 rounded-md text-xs font-medium transition-colors flex items-center gap-1.5',
              !previewMode
                ? 'bg-accent text-white'
                : 'bg-surface border border-surface-border text-text-secondary hover:border-accent/30'
            )}
          >
            <FileText className="w-3 h-3" />
            Source
          </button>
        </div>

        <div className="flex items-center gap-2">
          <button onClick={handleCopy} className="btn-outline text-xs flex items-center gap-1.5">
            {copied ? (
              <>
                <CheckCircle className="w-3 h-3 text-success" />
                Copied
              </>
            ) : (
              <>
                <Copy className="w-3 h-3" />
                Copy
              </>
            )}
          </button>
          <button
            onClick={handleExportMarkdown}
            disabled={exporting === 'md'}
            className="btn-outline text-xs flex items-center gap-1.5"
          >
            {exporting === 'md' ? (
              <Loader2 className="w-3 h-3 animate-spin" />
            ) : (
              <Download className="w-3 h-3" />
            )}
            Export Markdown
          </button>
          <button
            onClick={handleExportPDF}
            disabled={exporting === 'pdf'}
            className="btn-primary text-xs flex items-center gap-1.5"
          >
            {exporting === 'pdf' ? (
              <Loader2 className="w-3 h-3 animate-spin" />
            ) : (
              <FileDown className="w-3 h-3" />
            )}
            Export PDF
          </button>
        </div>
      </div>

      {/* Content */}
      <div className="card-forensic">
        {previewMode ? (
          <div className="prose prose-invert max-w-none report-preview">
            <div dangerouslySetInnerHTML={{ __html: markdownToHtml(markdown) }} />
          </div>
        ) : (
          <pre className="font-mono text-xs text-text-secondary leading-relaxed whitespace-pre-wrap overflow-x-auto max-h-[70vh] overflow-y-auto">
            {markdown}
          </pre>
        )}
      </div>
    </div>
  );
}

/**
 * Simple markdown-to-HTML converter for report preview.
 * Handles headings, bold, code, tables, lists, and horizontal rules.
 */
function markdownToHtml(md: string): string {
  let html = md
    // Escape HTML
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;');

  // Tables
  const lines = html.split('\n');
  let inTable = false;
  const processed: string[] = [];

  for (let i = 0; i < lines.length; i++) {
    const line = lines[i];
    if (line.startsWith('|') && line.endsWith('|')) {
      if (!inTable) {
        inTable = true;
        processed.push('<table style="border-collapse:collapse;width:100%;margin:12px 0;font-size:13px;">');
      }
      // Skip separator row
      if (line.match(/^\|[\s-:|]+\|$/)) continue;

      const cells = line
        .split('|')
        .slice(1, -1)
        .map((c) => c.trim());
      const tag = !inTable || processed[processed.length - 1]?.includes('<table') ? 'th' : 'td';
      const style =
        tag === 'th'
          ? 'style="border:1px solid #30363D;padding:8px;background:#1C2128;color:#8B949E;text-align:left;"'
          : 'style="border:1px solid #30363D;padding:8px;color:#E6EDF3;"';
      processed.push(
        `<tr>${cells.map((c) => `<${tag} ${style}>${c}</${tag}>`).join('')}</tr>`
      );
    } else {
      if (inTable) {
        inTable = false;
        processed.push('</table>');
      }
      processed.push(line);
    }
  }
  if (inTable) processed.push('</table>');

  html = processed.join('\n');

  // Headings
  html = html.replace(/^### (.+)$/gm, '<h3 style="color:#E6EDF3;margin-top:16px;font-size:16px;">$1</h3>');
  html = html.replace(/^## (.+)$/gm, '<h2 style="color:#1F6FEB;margin-top:24px;font-size:18px;border-bottom:1px solid #30363D;padding-bottom:6px;">$1</h2>');
  html = html.replace(/^# (.+)$/gm, '<h1 style="color:#E6EDF3;font-size:22px;border-bottom:2px solid #1F6FEB;padding-bottom:8px;">$1</h1>');

  // Bold
  html = html.replace(/\*\*(.+?)\*\*/g, '<strong style="color:#E6EDF3;">$1</strong>');

  // Italic
  html = html.replace(/\*(.+?)\*/g, '<em style="color:#8B949E;">$1</em>');

  // Inline code
  html = html.replace(
    /`([^`]+)`/g,
    '<code style="background:#0D1117;padding:2px 6px;border-radius:3px;font-family:JetBrains Mono,monospace;font-size:12px;color:#E6EDF3;">$1</code>'
  );

  // Unordered lists
  html = html.replace(/^- (.+)$/gm, '<li style="color:#E6EDF3;margin:4px 0;">$1</li>');

  // Ordered lists
  html = html.replace(/^\d+\. (.+)$/gm, '<li style="color:#E6EDF3;margin:4px 0;">$1</li>');

  // Horizontal rule
  html = html.replace(/^---$/gm, '<hr style="border:none;border-top:1px solid #30363D;margin:20px 0;" />');

  // Paragraphs (empty lines)
  html = html.replace(/\n\n/g, '<br/><br/>');

  return html;
}
