#!/usr/bin/env bash
set -euo pipefail

# ── Colors ──────────────────────────────────────────────────────────
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
CYAN='\033[0;36m'
BOLD='\033[1m'
DIM='\033[2m'
NC='\033[0m'

CHECK="${GREEN}✓${NC}"
CROSS="${RED}✗${NC}"
WARN="${YELLOW}!${NC}"

# Portable sed -i (macOS requires '' argument, GNU does not)
_sed_i() {
    if [[ "${OSTYPE:-linux}" == "darwin"* ]]; then
        sed -i '' "$@"
    else
        sed -i "$@"
    fi
}

echo ""
echo -e "${CYAN}${BOLD}╔══════════════════════════════════════════════════════╗${NC}"
echo -e "${CYAN}${BOLD}║        DFIReballz — Setup Wizard                    ║${NC}"
echo -e "${CYAN}${BOLD}║        Digital Forensics & Cybercrime Platform       ║${NC}"
echo -e "${CYAN}${BOLD}╚══════════════════════════════════════════════════════╝${NC}"
echo ""

# ── Step 1: Prerequisites ──────────────────────────────────────────
echo -e "${BOLD}[1/7] Checking prerequisites...${NC}"
echo ""

ERRORS=0

if ! command -v docker &>/dev/null; then
    echo -e "  ${CROSS} Docker is not installed. Install Docker 25+ first."
    echo -e "     ${DIM}https://docs.docker.com/get-docker/${NC}"
    ERRORS=$((ERRORS + 1))
else
    DOCKER_VERSION=$(docker version --format '{{.Server.Version}}' 2>/dev/null || echo "unknown")
    echo -e "  ${CHECK} Docker: ${DOCKER_VERSION}"
fi

if ! docker compose version &>/dev/null; then
    echo -e "  ${CROSS} Docker Compose v2 is not installed."
    ERRORS=$((ERRORS + 1))
else
    COMPOSE_VERSION=$(docker compose version --short 2>/dev/null || echo "unknown")
    echo -e "  ${CHECK} Docker Compose: ${COMPOSE_VERSION}"
fi

if [ "$ERRORS" -gt 0 ]; then
    echo ""
    echo -e "  ${RED}${BOLD}Cannot continue — install missing prerequisites.${NC}"
    exit 1
fi

# Check Docker socket
DOCKER_GID_VALUE=$(stat -c '%g' /var/run/docker.sock 2>/dev/null || getent group docker 2>/dev/null | cut -d: -f3 || echo "999")
echo -e "  ${CHECK} Docker socket GID: ${DOCKER_GID_VALUE}"

# RAM check (Linux uses /proc/meminfo, macOS uses sysctl)
if [ -f /proc/meminfo ]; then
    TOTAL_RAM_KB=$(grep MemTotal /proc/meminfo | awk '{print $2}')
else
    TOTAL_RAM_KB=$(( $(sysctl -n hw.memsize 2>/dev/null || echo 0) / 1024 ))
fi
TOTAL_RAM_GB=$((TOTAL_RAM_KB / 1024 / 1024))
if [ "$TOTAL_RAM_GB" -ge 16 ]; then
    echo -e "  ${CHECK} RAM: ${TOTAL_RAM_GB} GB"
elif [ "$TOTAL_RAM_GB" -ge 8 ]; then
    echo -e "  ${WARN} RAM: ${TOTAL_RAM_GB} GB (16 GB recommended)"
else
    echo -e "  ${CROSS} RAM: ${TOTAL_RAM_GB} GB (need at least 8 GB)"
fi

# GPU check
GPU_AVAILABLE=false
if command -v nvidia-smi &>/dev/null; then
    GPU_NAME=$(nvidia-smi --query-gpu=name --format=csv,noheader 2>/dev/null | head -1 || echo "detected")
    echo -e "  ${CHECK} NVIDIA GPU: ${GPU_NAME}"
    GPU_AVAILABLE=true
else
    echo -e "  ${DIM}  ℹ  No NVIDIA GPU detected (optional — CPU mode works fine)${NC}"
fi
echo ""

# ── Step 2: Generate .env ──────────────────────────────────────────
echo -e "${BOLD}[2/7] Generating environment configuration...${NC}"
echo ""

if [ -f .env ]; then
    echo -e "  ${WARN} .env already exists — backing up to .env.backup"
    cp .env .env.backup
fi

# Generate secure random strings
generate_secret() {
    python3 -c "import secrets; print(secrets.token_urlsafe(32))" 2>/dev/null || \
    openssl rand -base64 32 2>/dev/null || \
    head -c 32 /dev/urandom | base64 | tr -d '=/+'
}

POSTGRES_PASSWORD=$(generate_secret)
SECRET_KEY=$(generate_secret)
WEBUI_SECRET_KEY=$(generate_secret)
MCPO_API_KEY=$(generate_secret)

cat > .env << EOF
# DFIReballz Environment Configuration
# Generated by setup wizard on $(date -u +"%Y-%m-%dT%H:%M:%SZ")

# ─── Database ────────────────────────────────────────────────────────
POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
POSTGRES_USER=dfireballz
POSTGRES_DB=dfireballz

# ─── Redis ───────────────────────────────────────────────────────────
REDIS_URL=redis://redis:6379/0

# ─── MCP Host Selection ─────────────────────────────────────────────
MCP_HOST=claude-code

# ─── API Keys (Threat Intelligence) ─────────────────────────────────
# Leave commented if you don't have the key. Do NOT set to empty.
# After adding keys, restart containers: make restart-threat
# VIRUSTOTAL_API_KEY=
# SHODAN_API_KEY=
# ABUSEIPDB_API_KEY=
# URLSCAN_API_KEY=
# VULNCHECK_API_KEY=

# ─── Open WebUI + Ollama ────────────────────────────────────────────
WEBUI_SECRET_KEY=${WEBUI_SECRET_KEY}
MCPO_API_KEY=${MCPO_API_KEY}
DOCKER_GID=${DOCKER_GID_VALUE}

# ─── GPU Support ─────────────────────────────────────────────────────
ENABLE_GPU=${GPU_AVAILABLE}

# ─── Application ─────────────────────────────────────────────────────
CASE_PREFIX=DFIR
LOG_LEVEL=INFO
SECRET_KEY=${SECRET_KEY}
EOF

echo -e "  ${CHECK} .env created with secure random passwords"
echo ""

# ── Step 3: Create directories ─────────────────────────────────────
echo -e "${BOLD}[3/7] Creating data directories...${NC}"
echo ""

mkdir -p cases evidence reports results
mkdir -p output/{findings,screenshots,logs,exports,timelines}

echo -e "  ${CHECK} cases/        — Case working files"
echo -e "  ${CHECK} evidence/     — Evidence files (mounted read-only in containers)"
echo -e "  ${CHECK} reports/      — Generated forensic reports"
echo -e "  ${CHECK} results/      — Session data and structured output"
echo -e "  ${CHECK} output/       — Host-visible investigation output:"
echo -e "     ${DIM}├── findings/    — Analysis results and summaries${NC}"
echo -e "     ${DIM}├── screenshots/ — Captured screenshots and visual evidence${NC}"
echo -e "     ${DIM}├── logs/        — Investigation activity logs${NC}"
echo -e "     ${DIM}├── exports/     — Exported artifacts (carved files, objects)${NC}"
echo -e "     ${DIM}└── timelines/   — Reconstructed event timelines${NC}"
echo ""

# ── Step 4: MCP Host selection ─────────────────────────────────────
echo -e "${BOLD}[4/7] Choose your AI host${NC}"
echo ""
echo -e "  ${BOLD}Which AI client will you use with DFIReballz?${NC}"
echo ""
echo -e "  ${CYAN}1)${NC} Claude Code in Docker       ${DIM}(recommended — fully containerized, zero install)${NC}"
echo -e "  ${CYAN}2)${NC} Claude Code on host          ${DIM}(you already have Claude Code installed)${NC}"
echo -e "  ${CYAN}3)${NC} Claude Desktop               ${DIM}(GUI app — macOS, Windows, Linux)${NC}"
echo -e "  ${CYAN}4)${NC} ChatGPT                      ${DIM}(requires SSE proxy — see guide after setup)${NC}"
echo -e "  ${CYAN}5)${NC} MCPHost + Ollama             ${DIM}(fully local, no cloud — requires Go)${NC}"
echo -e "  ${CYAN}6)${NC} Open WebUI + Ollama          ${DIM}(web UI for local models)${NC}"
echo ""
read -rp "  Choice [1]: " MCP_CHOICE
MCP_CHOICE=${MCP_CHOICE:-1}

case $MCP_CHOICE in
    1) MCP_HOST="claude-code" ;;
    2) MCP_HOST="claude-code" ;;
    3) MCP_HOST="claude-desktop" ;;
    4) MCP_HOST="chatgpt" ;;
    5) MCP_HOST="mcphost" ;;
    6) MCP_HOST="open-webui" ;;
    *) MCP_HOST="claude-code" ;;
esac

_sed_i "s|MCP_HOST=claude-code|MCP_HOST=${MCP_HOST}|" .env
echo ""
echo -e "  ${CHECK} MCP Host: ${MCP_HOST}"
echo ""

# ── Step 5: API Keys ──────────────────────────────────────────────
echo -e "${BOLD}[5/7] API Keys (optional — press Enter to skip any)${NC}"
echo ""
echo -e "  ${DIM}These threat-intel services offer free tiers. Sign up first if you haven't.${NC}"
echo -e "  ${DIM}You can add or change keys later in .env — no need to re-run setup.${NC}"
echo ""

_prompt_key() {
    local service="$1" env_var="$2" url="$3"
    echo -e "  ${DIM}${url}${NC}"
    read -rp "  ${service} API Key: " KEY_VALUE
    if [ -n "$KEY_VALUE" ]; then
        # Uncomment the line and set the value
        _sed_i "s|^# *${env_var}=.*|${env_var}=${KEY_VALUE}|" .env
        echo -e "  ${CHECK} Saved"
    else
        echo -e "  ${DIM}  Skipped (add later in .env, then: make restart-threat)${NC}"
    fi
    echo ""
}

_prompt_key "VirusTotal"  "VIRUSTOTAL_API_KEY" "https://www.virustotal.com/gui/my-apikey"
_prompt_key "Shodan"      "SHODAN_API_KEY"     "https://account.shodan.io/"
_prompt_key "AbuseIPDB"   "ABUSEIPDB_API_KEY"  "https://www.abuseipdb.com/account/api"
_prompt_key "URLScan.io"  "URLSCAN_API_KEY"    "https://urlscan.io/user/signup"

# Claude Code auth (only for Docker or host-installed Claude Code)
if [ "$MCP_CHOICE" = "1" ]; then
    echo -e "  ${BOLD}Claude Code Docker Authentication${NC}"
    echo ""
    echo -e "  ${CYAN}a)${NC} API key           ${DIM}(pay-per-use — https://console.anthropic.com/settings/keys)${NC}"
    echo -e "  ${CYAN}b)${NC} OAuth token        ${DIM}(uses your Pro/Max subscription)${NC}"
    echo -e "  ${CYAN}c)${NC} Interactive login  ${DIM}(log in on first launch — credentials persist)${NC}"
    echo ""
    read -rp "  Auth method [c]: " AUTH_CHOICE
    AUTH_CHOICE=${AUTH_CHOICE:-c}

    case $AUTH_CHOICE in
        a|A)
            read -rp "  Anthropic API Key: " ANTHROPIC_KEY
            if [ -n "$ANTHROPIC_KEY" ]; then
                echo "" >> .env
                echo "# ─── Claude Code (Docker container) ──────────────────────────────" >> .env
                echo "ANTHROPIC_API_KEY=${ANTHROPIC_KEY}" >> .env
                echo -e "  ${CHECK} API key saved"
            fi
            ;;
        b|B)
            echo ""
            echo -e "  ${DIM}Run 'claude setup-token' on your host to generate a token.${NC}"
            read -rp "  OAuth Token: " OAUTH_TOKEN
            if [ -n "$OAUTH_TOKEN" ]; then
                echo "" >> .env
                echo "# ─── Claude Code (Docker container) ──────────────────────────────" >> .env
                echo "CLAUDE_CODE_OAUTH_TOKEN=${OAUTH_TOKEN}" >> .env
                echo -e "  ${CHECK} OAuth token saved"
            fi
            ;;
        *)
            echo -e "  ${CHECK} Interactive login — you'll be prompted on first 'make claude-code'"
            ;;
    esac
    echo ""
fi

# ── Step 6: Pull images ───────────────────────────────────────────
echo -e "${BOLD}[6/7] Pulling pre-built Docker images from Docker Hub...${NC}"
echo -e "  ${DIM}Images: docker.io/crhacky/dfireballz:*${NC}"
echo ""

if docker compose pull; then
    echo ""
    echo -e "  ${CHECK} All images pulled successfully"
else
    echo ""
    echo -e "  ${CROSS} Some images failed to pull — check the errors above."
    echo -e "  ${DIM}  You can retry later with 'make pull' or build locally with 'make build'.${NC}"
    echo ""
    read -rp "  Continue setup anyway? [y/N] " CONTINUE_PULL
    case "$CONTINUE_PULL" in [yY]*) ;; *) exit 1 ;; esac
fi

echo ""

# ── Step 7: Generate MCP configuration ────────────────────────────
echo -e "${BOLD}[7/7] Generating MCP configuration...${NC}"
echo ""
bash scripts/configure_mcp.sh --host "${MCP_HOST}"

# ── Post-setup guide ──────────────────────────────────────────────
echo ""
echo -e "${GREEN}${BOLD}══════════════════════════════════════════════════════${NC}"
echo -e "${GREEN}${BOLD}  Setup complete!${NC}"
echo -e "${GREEN}${BOLD}══════════════════════════════════════════════════════${NC}"
echo ""

case $MCP_CHOICE in
    1)
        echo -e "  ${BOLD}Next steps — Claude Code (Docker):${NC}"
        echo ""
        echo -e "  ${CYAN}1.${NC} Start the platform:     ${BOLD}make start${NC}"
        echo -e "  ${CYAN}2.${NC} Launch Claude Code:      ${BOLD}make claude-code${NC}"
        echo -e "  ${CYAN}3.${NC} Start investigating!"
        echo ""
        echo -e "  ${DIM}All findings will appear in ./output/ on your host machine.${NC}"
        ;;
    2)
        echo -e "  ${BOLD}Next steps — Claude Code (Host):${NC}"
        echo ""
        echo -e "  ${CYAN}1.${NC} Start the platform:     ${BOLD}make start${NC}"
        echo -e "  ${CYAN}2.${NC} Open Claude Code in this directory"
        echo -e "     ${DIM}MCP tools are auto-discovered from .mcp.json${NC}"
        echo -e "  ${CYAN}3.${NC} Start investigating!"
        echo ""
        echo -e "  ${DIM}Reports appear in ./reports/ — results in ./results/${NC}"
        ;;
    3)
        echo -e "  ${BOLD}Next steps — Claude Desktop:${NC}"
        echo ""
        echo -e "  ${CYAN}1.${NC} Start the platform:     ${BOLD}make start${NC}"
        echo -e "  ${CYAN}2.${NC} Copy MCP config to Claude Desktop:"
        if [[ "${OSTYPE:-}" == "darwin"* ]]; then
            CONFIG_PATH="~/Library/Application Support/Claude/claude_desktop_config.json"
        elif [[ "${OSTYPE:-}" == "msys" || "${OSTYPE:-}" == "cygwin" ]]; then
            CONFIG_PATH="%APPDATA%\\Claude\\claude_desktop_config.json"
        else
            CONFIG_PATH="~/.config/Claude/claude_desktop_config.json"
        fi
        echo ""
        echo -e "     ${DIM}Merge the contents of .mcp.json into:${NC}"
        echo -e "     ${BOLD}${CONFIG_PATH}${NC}"
        echo ""
        echo -e "     ${DIM}Or run this to auto-merge (creates backup):${NC}"
        echo -e "     ${BOLD}bash scripts/install-claude-desktop.sh${NC}"
        echo ""
        echo -e "  ${CYAN}3.${NC} Restart Claude Desktop"
        echo -e "  ${CYAN}4.${NC} MCP tools appear automatically — start investigating!"
        ;;
    4)
        echo -e "  ${BOLD}Next steps — ChatGPT:${NC}"
        echo ""
        echo -e "  ${YELLOW}Note: ChatGPT uses HTTP/SSE transport, not stdio.${NC}"
        echo -e "  ${DIM}You need the mcpo proxy to bridge MCP servers as HTTP endpoints.${NC}"
        echo ""
        echo -e "  ${CYAN}1.${NC} Start the platform with OpenWebUI profile:"
        echo -e "     ${BOLD}make start-openwebui${NC}"
        echo ""
        echo -e "  ${CYAN}2.${NC} In ChatGPT (Developer Mode):"
        echo -e "     Settings > Connectors > Advanced > Developer Mode"
        echo -e "     Add MCP server URL: ${BOLD}http://YOUR_HOST_IP:8812${NC}"
        echo ""
        echo -e "  ${CYAN}3.${NC} Each MCP server is available at:"
        echo -e "     ${DIM}http://YOUR_HOST_IP:8812/kali-forensics/${NC}"
        echo -e "     ${DIM}http://YOUR_HOST_IP:8812/osint/${NC}"
        echo -e "     ${DIM}http://YOUR_HOST_IP:8812/threat-intel/${NC}"
        echo -e "     ${DIM}... (see README for full list)${NC}"
        echo ""
        echo -e "  ${YELLOW}Important: Your machine must be reachable from the internet${NC}"
        echo -e "  ${YELLOW}for ChatGPT to connect (or use a tunnel like ngrok/cloudflared).${NC}"
        ;;
    5)
        echo -e "  ${BOLD}Next steps — MCPHost + Ollama:${NC}"
        echo ""
        echo -e "  ${CYAN}1.${NC} Install Ollama:          ${BOLD}curl -fsSL https://ollama.ai/install.sh | sh${NC}"
        echo -e "  ${CYAN}2.${NC} Install MCPHost:         ${BOLD}go install github.com/mark3labs/mcphost@latest${NC}"
        echo -e "  ${CYAN}3.${NC} Pull a model:            ${BOLD}ollama pull qwen3:8b${NC}"
        echo -e "  ${CYAN}4.${NC} Start DFIReballz:        ${BOLD}make start${NC}"
        echo -e "  ${CYAN}5.${NC} Launch MCPHost:           ${BOLD}mcphost -m ollama/qwen3:8b --config ~/.mcphost.yml${NC}"
        echo ""
        echo -e "  ${DIM}Config written to ~/.mcphost.yml${NC}"
        echo ""
        echo -e "  ${BOLD}Recommended models:${NC}"
        echo -e "  ${DIM}  qwen3:8b    — Excellent tool calling, 8 GB RAM${NC}"
        echo -e "  ${DIM}  qwen3:14b   — Better reasoning, 16 GB RAM${NC}"
        echo -e "  ${DIM}  llama3.1:8b — Good tool calling, 8 GB RAM${NC}"
        ;;
    6)
        echo -e "  ${BOLD}Next steps — Open WebUI + Ollama:${NC}"
        echo ""
        echo -e "  ${CYAN}1.${NC} Start everything:       ${BOLD}make start-openwebui${NC}"
        echo -e "  ${CYAN}2.${NC} Open http://localhost:8080"
        echo -e "  ${CYAN}3.${NC} Register MCP tools:"
        echo -e "     Admin Panel > Settings > External Tools"
        echo -e "     Add each: ${DIM}http://mcpo:8000/<server-name>/${NC}"
        echo ""
        ;;
esac

echo -e "  ${BOLD}Host directories:${NC}"
echo -e "  ${DIM}  ./evidence/   → Place evidence files here (mounted read-only)${NC}"
echo -e "  ${DIM}  ./cases/      → Working case files${NC}"
echo -e "  ${DIM}  ./reports/    → Generated forensic reports${NC}"
echo -e "  ${DIM}  ./results/    → Session data and structured output${NC}"
echo -e "  ${DIM}  ./output/     → All investigation output (findings, screenshots, logs)${NC}"
echo ""
echo -e "  ${BOLD}Useful commands:${NC}"
echo -e "  ${DIM}  make status   — Container health overview${NC}"
echo -e "  ${DIM}  make health   — MCP server health check${NC}"
echo -e "  ${DIM}  make help     — All available commands${NC}"
echo ""
