#!/usr/bin/env bash
set -euo pipefail

echo "╔══════════════════════════════════════════╗"
echo "║     DFIReballz Setup Wizard              ║"
echo "║     Digital Forensics Platform           ║"
echo "╚══════════════════════════════════════════╝"
echo ""

# Check prerequisites
echo "[1/6] Checking prerequisites..."

if ! command -v docker &>/dev/null; then
    echo "ERROR: Docker is not installed. Install Docker 25+ first."
    exit 1
fi

if ! docker compose version &>/dev/null; then
    echo "ERROR: Docker Compose v2 is not installed."
    exit 1
fi

echo "  Docker: $(docker --version | head -1)"
echo "  Docker Compose: $(docker compose version | head -1)"

# Check for NVIDIA GPU (optional)
if command -v nvidia-smi &>/dev/null; then
    echo "  NVIDIA GPU: Detected"
    GPU_AVAILABLE=true
else
    echo "  NVIDIA GPU: Not detected (GPU features disabled)"
    GPU_AVAILABLE=false
fi
echo ""

# Generate .env file
echo "[2/6] Generating environment configuration..."

if [ -f .env ]; then
    echo "  .env file already exists. Backing up to .env.backup"
    cp .env .env.backup
fi

# Generate secure random strings
generate_secret() {
    python3 -c "import secrets; print(secrets.token_urlsafe(32))" 2>/dev/null || \
    openssl rand -base64 32 2>/dev/null || \
    head -c 32 /dev/urandom | base64 | tr -d '=/+'
}

POSTGRES_PASSWORD=$(generate_secret)
SECRET_KEY=$(generate_secret)
WEBUI_SECRET_KEY=$(generate_secret)
MCPO_API_KEY=$(generate_secret)

cat > .env << EOF
# DFIReballz Environment Configuration
# Generated by setup wizard on $(date -u +"%Y-%m-%dT%H:%M:%SZ")

# ─── Database ────────────────────────────────────────────────────────
POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
POSTGRES_USER=dfireballz
POSTGRES_DB=dfireballz

# ─── Redis ───────────────────────────────────────────────────────────
REDIS_URL=redis://redis:6379/0

# ─── MCP Host Selection ─────────────────────────────────────────────
MCP_HOST=claude-code

# ─── API Keys (fill in your keys) ───────────────────────────────────
VIRUSTOTAL_API_KEY=
SHODAN_API_KEY=
ABUSEIPDB_API_KEY=
URLSCAN_API_KEY=
VULNCHECK_API_KEY=

# ─── Open WebUI + Ollama ────────────────────────────────────────────
WEBUI_SECRET_KEY=${WEBUI_SECRET_KEY}
MCPO_API_KEY=${MCPO_API_KEY}
DOCKER_GID=$(getent group docker 2>/dev/null | cut -d: -f3 || echo "999")

# ─── GPU Support ─────────────────────────────────────────────────────
ENABLE_GPU=${GPU_AVAILABLE}

# ─── Application ─────────────────────────────────────────────────────
CASE_PREFIX=DFIR
LOG_LEVEL=INFO
SECRET_KEY=${SECRET_KEY}
EOF

echo "  .env file created with secure random passwords"
echo ""

# Create directories
echo "[3/6] Creating data directories..."
mkdir -p cases evidence reports
echo "  cases/ evidence/ reports/ directories ready"
echo ""

# MCP Host selection
echo "[4/6] MCP Host Configuration"
echo "  Select your AI host:"
echo "    1) Claude Code (recommended)"
echo "    2) Claude Desktop"
echo "    3) MCPHost + Ollama"
echo "    4) Open WebUI + Ollama"
echo ""
read -rp "  Choice [1]: " MCP_CHOICE
MCP_CHOICE=${MCP_CHOICE:-1}

case $MCP_CHOICE in
    1) MCP_HOST="claude-code" ;;
    2) MCP_HOST="claude-desktop" ;;
    3) MCP_HOST="mcphost" ;;
    4) MCP_HOST="open-webui" ;;
    *) MCP_HOST="claude-code" ;;
esac

sed -i "s|MCP_HOST=claude-code|MCP_HOST=${MCP_HOST}|" .env
echo "  MCP Host set to: ${MCP_HOST}"
echo ""

# API Keys (optional)
echo "[5/6] API Keys (optional — press Enter to skip)"
echo ""

read -rp "  VirusTotal API Key: " VT_KEY
if [ -n "$VT_KEY" ]; then
    sed -i "s|VIRUSTOTAL_API_KEY=|VIRUSTOTAL_API_KEY=${VT_KEY}|" .env
fi

read -rp "  Shodan API Key: " SHODAN_KEY
if [ -n "$SHODAN_KEY" ]; then
    sed -i "s|SHODAN_API_KEY=|SHODAN_API_KEY=${SHODAN_KEY}|" .env
fi

read -rp "  AbuseIPDB API Key: " ABUSE_KEY
if [ -n "$ABUSE_KEY" ]; then
    sed -i "s|ABUSEIPDB_API_KEY=|ABUSEIPDB_API_KEY=${ABUSE_KEY}|" .env
fi

read -rp "  URLScan.io API Key: " URLSCAN_KEY
if [ -n "$URLSCAN_KEY" ]; then
    sed -i "s|URLSCAN_API_KEY=|URLSCAN_API_KEY=${URLSCAN_KEY}|" .env
fi

echo ""

# Build
echo "[6/6] Building Docker images..."
echo "  This may take several minutes on first run."
echo ""

docker compose build --parallel

echo ""
echo "══════════════════════════════════════════════"
echo "  Setup complete!"
echo ""
echo "  Next steps:"
echo "    make start              — Start DFIReballz"
echo "    make configure-mcp      — Generate MCP config for ${MCP_HOST}"
echo ""
echo "  Dashboard: http://localhost:3000"
echo "  API:       http://localhost:8800"
echo "══════════════════════════════════════════════"
